### ISSUE TITLE
Add `containerMode` option to the spec of Runner/RunnerDeployment

### ISSUE THREAD

**Issue by thboop** [thboop/actions-runner-controller#1]
```
kind: Runner
metadata:
  name: example-runner3
spec:
  containerMode: kubernetes
```

If containerMode is set to kubernetes, we should set the following variables on the runner

```
ACTIONS_RUNNER_CONTAINER_HOOKS=${hookDirectory}/hooks.js
ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER=true
```

This will allow users to test this feature on one or more runners without doing it helm wide
