### ISSUE TITLE
Setup the spec for volume mounts

### ISSUE THREAD

**Issue by thboop** [thboop/actions-runner-controller#3]
Example is provided below. 
```
kind: Runner
spec:
# snip
  workVolumeClaimTemplate:
    storageClassName: "local-storage"
    resources:
      requests:
        storage: 1Gi #runner.hookStorageSize
```

We should take that and turn it into a 

```
  volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec: 
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "local-storage" # runner.hookStorageClass
              resources:
                requests:
                  storage: 1Gi #runner.hookStorageSize
  volumeMounts:
  - mountPath: /runner/_work
    name: work
```

on the actual pod

we will need to set
```
ACTIONS_RUNNER_CLAIM_NAME ={claimname}
ACTIONS_RUNNER_REQUIRE_SAME_NODE={true if ReadWriteOnce, false if ReadWriteMany}
```
